/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as PrivateSessionsRouteImport } from './routes/private-sessions'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChildrenClassesRouteImport } from './routes/children-classes'
import { Route as AdultClassesRouteImport } from './routes/adult-classes'
import { Route as AboutVictoriaRouteImport } from './routes/about-victoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChildrenClassesSummerRouteImport } from './routes/children-classes.summer'
import { Route as ChildrenClassesFallSpringRouteImport } from './routes/children-classes.fall-spring'
import { Route as AdultClassesNewToUsRouteImport } from './routes/adult-classes.new-to-us'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSessionsRoute = PrivateSessionsRouteImport.update({
  id: '/private-sessions',
  path: '/private-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenClassesRoute = ChildrenClassesRouteImport.update({
  id: '/children-classes',
  path: '/children-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultClassesRoute = AdultClassesRouteImport.update({
  id: '/adult-classes',
  path: '/adult-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVictoriaRoute = AboutVictoriaRouteImport.update({
  id: '/about-victoria',
  path: '/about-victoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenClassesSummerRoute = ChildrenClassesSummerRouteImport.update({
  id: '/summer',
  path: '/summer',
  getParentRoute: () => ChildrenClassesRoute,
} as any)
const ChildrenClassesFallSpringRoute =
  ChildrenClassesFallSpringRouteImport.update({
    id: '/fall-spring',
    path: '/fall-spring',
    getParentRoute: () => ChildrenClassesRoute,
  } as any)
const AdultClassesNewToUsRoute = AdultClassesNewToUsRouteImport.update({
  id: '/new-to-us',
  path: '/new-to-us',
  getParentRoute: () => AdultClassesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-victoria': typeof AboutVictoriaRoute
  '/adult-classes': typeof AdultClassesRouteWithChildren
  '/children-classes': typeof ChildrenClassesRouteWithChildren
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/private-sessions': typeof PrivateSessionsRoute
  '/social': typeof SocialRoute
  '/adult-classes/new-to-us': typeof AdultClassesNewToUsRoute
  '/children-classes/fall-spring': typeof ChildrenClassesFallSpringRoute
  '/children-classes/summer': typeof ChildrenClassesSummerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-victoria': typeof AboutVictoriaRoute
  '/adult-classes': typeof AdultClassesRouteWithChildren
  '/children-classes': typeof ChildrenClassesRouteWithChildren
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/private-sessions': typeof PrivateSessionsRoute
  '/social': typeof SocialRoute
  '/adult-classes/new-to-us': typeof AdultClassesNewToUsRoute
  '/children-classes/fall-spring': typeof ChildrenClassesFallSpringRoute
  '/children-classes/summer': typeof ChildrenClassesSummerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-victoria': typeof AboutVictoriaRoute
  '/adult-classes': typeof AdultClassesRouteWithChildren
  '/children-classes': typeof ChildrenClassesRouteWithChildren
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/private-sessions': typeof PrivateSessionsRoute
  '/social': typeof SocialRoute
  '/adult-classes/new-to-us': typeof AdultClassesNewToUsRoute
  '/children-classes/fall-spring': typeof ChildrenClassesFallSpringRoute
  '/children-classes/summer': typeof ChildrenClassesSummerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-victoria'
    | '/adult-classes'
    | '/children-classes'
    | '/contact'
    | '/instructors'
    | '/private-sessions'
    | '/social'
    | '/adult-classes/new-to-us'
    | '/children-classes/fall-spring'
    | '/children-classes/summer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-victoria'
    | '/adult-classes'
    | '/children-classes'
    | '/contact'
    | '/instructors'
    | '/private-sessions'
    | '/social'
    | '/adult-classes/new-to-us'
    | '/children-classes/fall-spring'
    | '/children-classes/summer'
  id:
    | '__root__'
    | '/'
    | '/about-victoria'
    | '/adult-classes'
    | '/children-classes'
    | '/contact'
    | '/instructors'
    | '/private-sessions'
    | '/social'
    | '/adult-classes/new-to-us'
    | '/children-classes/fall-spring'
    | '/children-classes/summer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutVictoriaRoute: typeof AboutVictoriaRoute
  AdultClassesRoute: typeof AdultClassesRouteWithChildren
  ChildrenClassesRoute: typeof ChildrenClassesRouteWithChildren
  ContactRoute: typeof ContactRoute
  InstructorsRoute: typeof InstructorsRoute
  PrivateSessionsRoute: typeof PrivateSessionsRoute
  SocialRoute: typeof SocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-sessions': {
      id: '/private-sessions'
      path: '/private-sessions'
      fullPath: '/private-sessions'
      preLoaderRoute: typeof PrivateSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children-classes': {
      id: '/children-classes'
      path: '/children-classes'
      fullPath: '/children-classes'
      preLoaderRoute: typeof ChildrenClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult-classes': {
      id: '/adult-classes'
      path: '/adult-classes'
      fullPath: '/adult-classes'
      preLoaderRoute: typeof AdultClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-victoria': {
      id: '/about-victoria'
      path: '/about-victoria'
      fullPath: '/about-victoria'
      preLoaderRoute: typeof AboutVictoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children-classes/summer': {
      id: '/children-classes/summer'
      path: '/summer'
      fullPath: '/children-classes/summer'
      preLoaderRoute: typeof ChildrenClassesSummerRouteImport
      parentRoute: typeof ChildrenClassesRoute
    }
    '/children-classes/fall-spring': {
      id: '/children-classes/fall-spring'
      path: '/fall-spring'
      fullPath: '/children-classes/fall-spring'
      preLoaderRoute: typeof ChildrenClassesFallSpringRouteImport
      parentRoute: typeof ChildrenClassesRoute
    }
    '/adult-classes/new-to-us': {
      id: '/adult-classes/new-to-us'
      path: '/new-to-us'
      fullPath: '/adult-classes/new-to-us'
      preLoaderRoute: typeof AdultClassesNewToUsRouteImport
      parentRoute: typeof AdultClassesRoute
    }
  }
}

interface AdultClassesRouteChildren {
  AdultClassesNewToUsRoute: typeof AdultClassesNewToUsRoute
}

const AdultClassesRouteChildren: AdultClassesRouteChildren = {
  AdultClassesNewToUsRoute: AdultClassesNewToUsRoute,
}

const AdultClassesRouteWithChildren = AdultClassesRoute._addFileChildren(
  AdultClassesRouteChildren,
)

interface ChildrenClassesRouteChildren {
  ChildrenClassesFallSpringRoute: typeof ChildrenClassesFallSpringRoute
  ChildrenClassesSummerRoute: typeof ChildrenClassesSummerRoute
}

const ChildrenClassesRouteChildren: ChildrenClassesRouteChildren = {
  ChildrenClassesFallSpringRoute: ChildrenClassesFallSpringRoute,
  ChildrenClassesSummerRoute: ChildrenClassesSummerRoute,
}

const ChildrenClassesRouteWithChildren = ChildrenClassesRoute._addFileChildren(
  ChildrenClassesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutVictoriaRoute: AboutVictoriaRoute,
  AdultClassesRoute: AdultClassesRouteWithChildren,
  ChildrenClassesRoute: ChildrenClassesRouteWithChildren,
  ContactRoute: ContactRoute,
  InstructorsRoute: InstructorsRoute,
  PrivateSessionsRoute: PrivateSessionsRoute,
  SocialRoute: SocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
